### ISSUE TITLE
panic: Starting dcrd results in panic

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrd#2368]
This issue has not been investigated but I wanted to capture the panic and not lose it.

I will close this if it turns out to be on my end.

```
$ dcrd
2020-09-24 11:05:23.430 [INF] DCRD: Version 1.6.0-pre (Go version go1.15.2 linux/amd64)
2020-09-24 11:05:23.431 [INF] DCRD: Home dir: ~/.dcrd2
2020-09-24 11:05:23.431 [INF] DCRD: Loading block database from '/home/marco/.dcrd/data/mainnet/blocks_ffldb'
2020-09-24 11:05:23.444 [INF] DCRD: Block database loaded
2020-09-24 11:05:23.447 [INF] INDX: Exists address index is enabled
2020-09-24 11:05:23.447 [INF] INDX: CF index is enabled
2020-09-24 11:05:23.459 [INF] CHAN: Loading block index...
2020-09-24 11:05:28.184 [INF] STKE: Stake database version 1 loaded
2020-09-24 11:05:28.185 [INF] CHAN: Blockchain database version info: chain: 7, compression: 1, block index: 3
2020-09-24 11:05:28.185 [INF] CHAN: Chain state: height 485191, hash 00000000000000000a54b5ada6528f2ff4e5436fc4517472c55ed9838b36cc48, total transactions 8324824, work 23731197272641387598933384, stake version 0
2020-09-24 11:05:28.194 [INF] RPCS: RPC server listening on [::1]:9109
2020-09-24 11:05:28.194 [INF] RPCS: RPC server listening on 127.0.0.1:9109
2020-09-24 11:05:28.194 [INF] CMGR: Server listening on 0.0.0.0:9108
2020-09-24 11:05:28.194 [INF] CMGR: Server listening on [::]:9108
2020-09-24 11:05:28.197 [INF] AMGR: Loaded 640 addresses from file '/home/marco/.dcrd/data/mainnet/peers.json'
2020-09-24 11:05:28.305 [INF] BMGR: New valid peer 198.12.112.19:9108 (outbound) (/dcrwire:0.4.0/dcrd:1.5.2/)
2020-09-24 11:05:28.306 [INF] BMGR: Syncing to block height 487687 from peer 198.12.112.19:9108
2020-09-24 11:05:28.328 [INF] BMGR: New valid peer 138.197.136.232:9108 (outbound) (/dcrwire:0.4.0/dcrd:1.5.0/)
2020-09-24 11:05:28.468 [INF] CMGR: 16 addresses found from seeder mainnet-seed-1.decred.org
2020-09-24 11:05:28.483 [INF] BMGR: New valid peer 137.74.198.133:9108 (outbound) (/dcrwire:0.4.0/dcrd:1.5.0(pre)/)
2020-09-24 11:05:28.550 [INF] BMGR: New valid peer [2a03:7380:3186:5e0f:39d8:785e:1d14:5b6d]:9108 (outbound) (/dcrwire:0.4.0/dcrd:1.5.2/)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x69c376]

goroutine 97 [running]:
github.com/decred/dcrd/database/v2/ffldb.rollbackOnPanic(0xc000293200)
        /home/marco/gopath/src/github.com/decred/dcrd/database/ffldb/db.go:1888 +0x77
panic(0xb1bfe0, 0x11c5480)
        /home/marco/go1.15/src/runtime/panic.go:969 +0x175
github.com/decred/dcrd/blockchain/v3.dbFetchUtxoEntry(0xe309c0, 0xc000293200, 0xc010828da0, 0x1, 0xc0106ba310, 0xc0178e3558)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/chainio.go:1170 +0x96
github.com/decred/dcrd/blockchain/v3.(*UtxoViewpoint).fetchUtxosMain.func1(0xe309c0, 0xc000293200, 0xc000293200, 0x0)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/utxoviewpoint.go:805 +0x105
github.com/decred/dcrd/database/v2/ffldb.(*db).View(0xc0001ae500, 0xc0106c3d80, 0x0, 0x0)
        /home/marco/gopath/src/github.com/decred/dcrd/database/ffldb/db.go:1911 +0xa2
github.com/decred/dcrd/blockchain/v3.(*UtxoViewpoint).fetchUtxosMain(0xc00bfce240, 0xe2a9a0, 0xc0001ae500, 0xc00bfce270, 0x0, 0xe1b0e0)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/utxoviewpoint.go:802 +0x8e
github.com/decred/dcrd/blockchain/v3.(*UtxoViewpoint).fetchInputUtxos(0xc00bfce240, 0xe2a9a0, 0xc0001ae500, 0xc0105a7280, 0x0, 0x0, 0x0)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/utxoviewpoint.go:916 +0x1d0
github.com/decred/dcrd/blockchain/v3.(*BlockChain).checkConnectBlock(0xc0000de000, 0xc01063c3c0, 0xc0105a7280, 0xc00eb8c500, 0xc00bfce240, 0xc0178e3940, 0xc00249c7f0, 0xc0178e3938, 0x40f850)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/validate.go:3645 +0x2bd
github.com/decred/dcrd/blockchain/v3.(*BlockChain).connectBestChain(0xc0000de000, 0xc01063c3c0, 0xc0105a7280, 0xc00eb8c500, 0x0, 0x0, 0xc0178e3a30, 0x4113f6)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/chain.go:1381 +0xd3e
github.com/decred/dcrd/blockchain/v3.(*BlockChain).maybeAcceptBlock(0xc0000de000, 0xc0105a7280, 0xc000000000, 0x0, 0xc0000fd340, 0x0)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/accept.go:135 +0x3e5
github.com/decred/dcrd/blockchain/v3.(*BlockChain).ProcessBlock(0xc0000de000, 0xc0105a7280, 0x0, 0x0, 0x0, 0x0)
        /home/marco/gopath/src/github.com/decred/dcrd/blockchain/process.go:92 +0x2bf
main.(*blockManager).processBlockAndOrphans(0xc00d4fba40, 0xc0105a7280, 0xc000000000, 0xc010756948, 0x40f801, 0xc0178e3c28, 0xc0178e3c28)
        /home/marco/gopath/src/github.com/decred/dcrd/blockmanager.go:1003 +0x69
main.(*blockManager).handleBlockMsg(0xc00d4fba40, 0xc010637b40)
        /home/marco/gopath/src/github.com/decred/dcrd/blockmanager.go:1098 +0x20e
main.(*blockManager).blockHandler(0xc00d4fba40)
        /home/marco/gopath/src/github.com/decred/dcrd/blockmanager.go:1674 +0xbbb
created by main.(*blockManager).Start
        /home/marco/gopath/src/github.com/decred/dcrd/blockmanager.go:2298 +0xd7
```

**Comment by marcopeereboom** [comment]
Turns out this happened due to running out of diskspace.
