### ISSUE TITLE
getwork panic when CurrentTemplate return nil template and nil error

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#2699]
I got a panic on a `getwork` request (recovered by http handler) on testnet3:

```
2021-08-04 14:43:43.184 [ERR] RPCS: http: panic serving [::1]:45694: runtime error: invalid memory address or nil pointer dereference                                                                                   
goroutine 2204410 [running]:                                                                                
net/http.(*conn).serve.func1(0xc000110460)                                                                  
        /usr/lib/go/src/net/http/server.go:1824 +0x153                                                      
panic(0xa40c80, 0x103bbe0)                                                                                                                                                                                              
        /usr/lib/go/src/runtime/panic.go:971 +0x499                                                         
github.com/decred/dcrd/internal/rpcserver.handleGetWorkRequest(0xc000270580, 0xc019d31e01, 0x7, 0x1, 0x2100000000721c2d)                                                                                                
        /decred/dcrd/internal/rpcserver/rpcserver.go:3753 +0x6f0                            
github.com/decred/dcrd/internal/rpcserver.handleGetWork(0xd2b558, 0xc016f24280, 0xc000270580, 0xa034c0, 0xc021be3098, 0x0, 0x0, 0x0, 0x0)                                                                               
        /decred/dcrd/internal/rpcserver/rpcserver.go:3951 +0x13f                            
github.com/decred/dcrd/internal/rpcserver.(*Server).standardCmdResult(0xc000270580, 0xd2b558, 0xc016f24280, 0xc021bca3c0, 0xc000118658, 0xa, 0xa00880, 0xc021bca370)
```

The above are release-v1.6 line numbers, but the code in question is the same on master:

https://github.com/decred/dcrd/blob/75b0f68a3583b8fb49e58151f283fdd63572e451/internal/rpcserver/rpcserver.go#L3689-L3691

It appears that `err` was `nil`, but this branch must have been taken because `template == nil`.  I don't know the significance of this circumstance.

**Comment by davecgh** [comment]
That should also be checking for a non-nil error.  That condition is normal during a reorg.  The `CurrentTemplate` method specifically calls out:

```
// NOTE: The returned template might be nil even if there is no error.  It is
// the responsibility of the caller to properly handle nil templates.
```

I'll open a PR to resolve that shortly.
