### ISSUE TITLE
dcrd panic

### ISSUE THREAD

**Issue by jrick** [decred/dcrd#286]
```
11:02:47 2016-07-15 [INF] CHAN: Adding orphan block 0000000002746301ebe86d938f865c0010305ba48d7cb22c2bfee3c08a8bbc76 with parent 00000000049128a3df2d3929528383bfd72cbcb2a88fc1e7591cc37a594f875c
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x7d6568]

goroutine 1504 [running]:
panic(0xc6a440, 0xc8200100d0)
        /home/jrick/go/src/runtime/panic.go:464 +0x3e6
github.com/decred/dcrd/addrmgr.NetAddressKey(0x0, 0x0, 0x0)
        /home/jrick/src/go/src/github.com/decred/dcrd/addrmgr/addrmanager.go:738 +0x28
main.(*serverPeer).addressKnown(0xc8326aa3c0, 0x0, 0xd8)
        /home/jrick/src/go/src/github.com/decred/dcrd/server.go:259 +0x21
main.(*serverPeer).pushAddrMsg(0xc8326aa3c0, 0xc8336fa000, 0xd8, 0x3ae)
        /home/jrick/src/go/src/github.com/decred/dcrd/server.go:287 +0xdc
main.(*serverPeer).OnGetAddr(0xc8326aa3c0, 0xc833190000, 0x13666b8)
        /home/jrick/src/go/src/github.com/decred/dcrd/server.go:973 +0x97
main.(*serverPeer).OnGetAddr-fm(0xc833190000, 0x13666b8)
        /home/jrick/src/go/src/github.com/decred/dcrd/server.go:1612 +0x34
github.com/decred/dcrd/peer.(*Peer).inHandler(0xc833190000)
        /home/jrick/src/go/src/github.com/decred/dcrd/peer/peer.go:1511 +0xf79
created by github.com/decred/dcrd/peer.(*Peer).start
        /home/jrick/src/go/src/github.com/decred/dcrd/peer/peer.go:1985 +0x282
```

This is with latest dcrd and all latest deps (dcrd checked out to `9146525767ed6d85c414a1bbad62d3779eeda784`).  I did not see the same panic after restarting.

**Comment by ironiridis** [comment]
What version of Go?
