### ISSUE TITLE
resource exhaustion and crash

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#293]
Just killed a dcrd on testnet that was eating CPU.  Then it spat out the following numerous times (minutes dumping to stdout):

```
goroutine 4877606140 [chan send]:
main.(*server).peerHandler.func4()
/home/u/go/src/github.com/decred/dcrd/server.go:1950 +0x3f
created by time.goFunc
        /home/u/go1.6/src/time/sleep.go:129 +0x3a
```

And the machine began swapping as memory ran out (~2GB).

On my build of dcrd 0.2.0, line 1950 is this channel send:

```
        //We need more peers, wake up in ten seconds and try again.
        if state.NeedMoreOutbound() {
            time.AfterFunc(10*time.Second, func() {
                s.wakeup <- struct{}{}
            })
        }
```

**Comment by alexlyp** [comment]
This was fixed in https://github.com/decred/dcrd/pull/314
