### ISSUE TITLE
Panic during block sync

### ISSUE THREAD

**Issue by ukane-philemon** [decred/dcrd#3212]
I'm running `dcrd version 1.9.0-pre+216132d7d (Go version go1.20.5 darwin/amd64)`

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x131c22a]

goroutine 51053 [running]:
github.com/decred/dcrd/wire.WriteMessageN({0x1869160, 0xc05387c168}, {0x0, 0x0}, 0x56bef2?, 0xc0?)
	/Users/{redacted}/DEsktop/decred/dcrd/wire/message.go:239 +0x6a
github.com/decred/dcrd/pe(0xc007317c00, {0x0?, 0x0})
	/Users/redacted}/DEsktop/decred/dcrd/peer/peer.go:997 +0x457
github.com/decred/dcrd/peer/v3.(*Peer).outHandler(0xc007317c00)
	/Users/redacted}/DEsktop/decred/dcrd/peer/peer.go:1613 +0x277
created by github.com/decred/dcrd/peer/v3.(*Peer).start
	/Users/redacted}/DEsktop/decred/dcrd/peer/peer.go:1958 +0x330
	
```

**Comment by jrick** [comment]
There have been significant improvements to the peer code since then, even in the past couple weeks.  I'd suggest upgrading and reporting any further issues if you hit them.

**Comment by davecgh** [comment]
I'm fairly certain this has already been addressed by other updates, but unfortunately this trace does not provide enough info to say definitively.

In any case, I'm closing this since it is addressed by #3213 insofar as if it turns out it really isn't fixed and happens again, we'll have a stack trace that pinpoints the exact cause and it can be addressed then.

Please update to the latest master.
