### ISSUE TITLE
panic: corrupt spend information

### ISSUE THREAD

**Issue by chappjc** [decred/dcrd#384]
On testnet:

```
panic: corrupt spend information for 00000000006dff15d66b0ebb5c8ce9e6a7e93e297a5f27d8e8a6e8228e1a583d: unable to decode stxo for 911ad0de9b57f7ff0cad8da17157bd47859b952e383fedadf898097f6e21a8f9:2: no serialized bytes

goroutine 71 [running]:
panic(0xacd9e0, 0xc42dcdc6f0)
        /home/jon/go1.7/src/runtime/panic.go:500 +0x1a1
main.(*blockManager).handleBlockMsg(0xc4201f2180, 0xc43046c330)
        /home/jon/go/src/github.com/decred/dcrd/blockmanager.go:1238 +0x19a9
main.(*blockManager).blockHandler(0xc4201f2180)
        /home/jon/go/src/github.com/decred/dcrd/blockmanager.go:1859 +0x2310
created by main.(*blockManager).Start
        /home/jon/go/src/github.com/decred/dcrd/blockmanager.go:2530 +0x12b
```

**Comment by cjepson** [comment]
Should have been fixed by https://github.com/decred/dcrd/commit/16f6dab4021482b82ef4960144c2beaba0154bfa

**Comment by dajohi** [comment]
@chappjc Do you still see this issue?
