### ISSUE TITLE
Crash on inital sync of blockchain (v1.1.2)

### ISSUE THREAD

**Issue by AlanBarber** [decred/dcrd#947]
wiped out my .dcrd data folder on ubuntu 14.04 box and started dcrd back up to resync the full database but got this error after a while.  I restarted the app and it continued to run FYI.

```
2017-12-15 23:48:32.717 [INF] BMGR: Processed 36 blocks in the last 10.03s (1215 transactions, 720 tickets, 174 votes, 1
1 revocations, height 64583, 2016-09-18 18:33:08 +0000 UTC)
2017-12-15 23:48:42.876 [INF] BMGR: Processed 65 blocks in the last 10.15s (692 transactions, 1300 tickets, 320 votes, 3
 revocations, height 64648, 2016-09-19 00:29:29 +0000 UTC)
2017-12-15 23:48:52.905 [INF] BMGR: Processed 302 blocks in the last 10.02s (1019 transactions, 253 tickets, 1474 votes,
 31 revocations, height 64950, 2016-09-20 03:53:16 +0000 UTC)
2017-12-15 23:49:03.280 [INF] BMGR: Processed 147 blocks in the last 10.37s (1143 transactions, 486 tickets, 723 votes,
34 revocations, height 65097, 2016-09-20 17:01:43 +0000 UTC)
2017-12-15 23:49:13.352 [INF] BMGR: Processed 65 blocks in the last 10.07s (1146 transactions, 1300 tickets, 319 votes,
7 revocations, height 65162, 2016-09-20 22:20:20 +0000 UTC)
panic: runtime error: slice bounds out of range [recovered]
        panic: runtime error: slice bounds out of range

goroutine 32 [running]:
github.com/decred/dcrd/database/ffldb.rollbackOnPanic(0xc4253b6240)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/db.go:1890 +0x77
panic(0xa540c0, 0xfcd840)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/memdb.(*dbIter).fill(0xc426226100, 0xc80100, 0xc42ca
1ea98)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/memdb/memdb.go:41 +0x305
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/memdb.(*dbIter).Next(0xc426226100, 0xc434f8bd00)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/memdb/memdb.go:130 +0x14
2
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb.(*tOps).createFrom(0xc420492c00, 0xf9b2e0, 0xc426226
100, 0x0, 0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/table.go:328 +0xd8
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb.(*Transaction).flush(0xc429247180, 0x11, 0x2c)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/db_transaction.go:90 +0x
13f
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb.(*Transaction).put(0xc429247180, 0x0, 0xc427d9fa70, 0x24, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/db_transaction.go:114 +0x193
github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb.(*Transaction).Delete(0xc429247180, 0xc427d9fa70, 0x24, 0x24, 0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/vendor/github.com/btcsuite/goleveldb/leveldb/db_transaction.go:151 +0x108
github.com/decred/dcrd/database/ffldb.(*dbCache).commitTreaps.func1.2(0xc427d9fa70, 0x24, 0x24, 0x1020388, 0x0, 0x0, 0xc4319fa601)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:458 +0x75
github.com/decred/dcrd/database/internal/treap.(*Immutable).ForEach(0xc428b222a0, 0xc427a8c1c0)
        /home/dhill/.go/src/github.com/decred/dcrd/database/internal/treap/immutable.go:345 +0x3e8
github.com/decred/dcrd/database/ffldb.(*dbCache).commitTreaps.func1(0xc429247180, 0xc429247180, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:457 +0x134
github.com/decred/dcrd/database/ffldb.(*dbCache).updateDB(0xc4200522a0, 0xc4319fac08, 0x1d3ee9625a345f81, 0x5a345f81)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:418 +0x6c
github.com/decred/dcrd/database/ffldb.(*dbCache).commitTreaps(0xc4200522a0, 0xf908e0, 0xc428b22220, 0xf908e0, 0xc428b222a0, 0x45db46b9d5, 0xc4319faca0)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:442 +0x9a
github.com/decred/dcrd/database/ffldb.(*dbCache).flush(0xc4200522a0, 0xc4253b6240, 0xc4290ffe01)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:501 +0x112
github.com/decred/dcrd/database/ffldb.(*dbCache).commitTx(0xc4200522a0, 0xc4253b6240, 0xe, 0xe)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/dbcache.go:560 +0x6b
github.com/decred/dcrd/database/ffldb.(*transaction).writePendingAndCommit(0xc4253b6240, 0xc85b80, 0xc4253b6240)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/db.go:1728 +0x63a
github.com/decred/dcrd/database/ffldb.(*transaction).Commit(0xc4253b6240, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/db.go:1762 +0xb4
github.com/decred/dcrd/database/ffldb.(*db).Update(0xc420494000, 0xc430015680, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/database/ffldb/db.go:1957 +0xfc
github.com/decred/dcrd/blockchain.(*BlockChain).connectBlock(0xc4204b2c00, 0xc42dc5ed00, 0xc426b4b480, 0xc421738030, 0xc424ebe800, 0x28, 0x45, 0xc4230c3830, 0x2)
        /home/dhill/.go/src/github.com/decred/dcrd/blockchain/chain.go:1178 +0x452
github.com/decred/dcrd/blockchain.(*BlockChain).connectBestChain(0xc4204b2c00, 0xc42dc5ed00, 0xc426b4b480, 0xc400000001, 0x0, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/blockchain/chain.go:1907 +0xd6d
github.com/decred/dcrd/blockchain.(*BlockChain).maybeAcceptBlock(0xc4204b2c00, 0xc426b4b480, 0x1, 0x0, 0x0, 0x1000880)
        /home/dhill/.go/src/github.com/decred/dcrd/blockchain/accept.go:300 +0x37e
github.com/decred/dcrd/blockchain.(*BlockChain).ProcessBlock(0xc4204b2c00, 0xc426b4b480, 0xc400000001, 0xc420850000, 0x0, 0x0)
        /home/dhill/.go/src/github.com/decred/dcrd/blockchain/process.go:228 +0x488
main.(*blockManager).handleBlockMsg(0xc4200102c0, 0xc429a8fd70)
        /home/dhill/.go/src/github.com/decred/dcrd/blockmanager.go:1016 +0x1ce
main.(*blockManager).blockHandler(0xc4200102c0)
        /home/dhill/.go/src/github.com/decred/dcrd/blockmanager.go:1662 +0x1ec8
created by main.(*blockManager).Start
        /home/dhill/.go/src/github.com/decred/dcrd/blockmanager.go:2283 +0xe8
```

**Comment by davecgh** [comment]
Thanks for the report.  We'll dig into this deeper to verify, but on a quick look, this really looks like an issue with failing hardware.  Most likely memory because the error occurred during iteration through leveldb's internal memory database that it keeps in between writes which should not be able to fail unless there is memory corruption.

**Comment by davecgh** [comment]
@AlanBarber reported on slack that memtest did indeed identify failing memory.

"memtest found a single bad byte on one of the sticks of ram"

**Comment by AlanBarber** [comment]
yup, seems to be hardware failure. i'll close the issue. 

Thanks!
